import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

async function main() {
  await prisma.continent.createMany({
    data: [
      { name: "Europe" }, 
      { name: "North America" }, 
      { name: "South America" }
    ],
  });

  await prisma.user.create({
    data: {
      email: "viniciusfernandes643@gmail.com",
      id: "WRCcT6MnWKW1enpKHMJ9nQQWrHm1",
      name: "Vinicius Fernandes",
    }}
  )



  await prisma.country.createMany({
    data: [
      { name: "Brazil", continentId: 3 },
      { name: "France", continentId: 1 },
      { name: "Italy", continentId: 1 },
      { name: "USA", continentId: 2 },
    ],
  });

  await prisma.city.createMany({
    data: [
      { name: "Paris", countryId: 2 },
      { name: "Rio de Janeiro", countryId: 1 },
      { name: "Rome", countryId: 3 },
      { name: "New York", countryId: 4 },
    ],
  });

  await prisma.types.createMany({
    data: [
      { name: "Adventure" },
      { name: "Cultural" },
      { name: "Historical" },
      { name: "Relaxing" },
    ],
  });

  await prisma.tour.createMany({
    data: [
      {
        name: "Tour 1 in New York",
        urlImage: "https://mybucketomyproject.s3.us-east-2.amazonaws.com/NewYork+(1).jpg",
        countryId: 4,
        cityId: 4,
        initialDate: new Date("2024-09-01"),
        finalDate: new Date("2024-09-10"),
        avarageRating: 4.5,
        duration: 7,
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus imperdiet, nulla vel tempor consectetur.",
        maxPeople: 10,
        minAge: 5,
        overview: "Experience the best of New York.",
        typeId: 1,
        price: 1500,
      },
      {
        name: "Tour 2 in Rio",
        urlImage: "https://mybucketomyproject.s3.us-east-2.amazonaws.com/Rio+(1).jpg",
        countryId: 1,
        cityId: 2,
        initialDate: new Date("2024-10-01"),
        finalDate: new Date("2024-10-10"),
        avarageRating: 4.7,
        duration: 8,
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque nec diam et turpis pretium tincidunt.",
        maxPeople: 12,
        minAge: 7,
        overview: "Enjoy Rio's vibrant atmosphere.",
        typeId: 2,
        price: 1200,
      },
      {
        name: "Tour 3 in Paris",
        urlImage: "https://mybucketomyproject.s3.us-east-2.amazonaws.com/Paris+(1).jpg",
        countryId: 2,
        cityId: 1,
        initialDate: new Date("2024-11-01"),
        finalDate: new Date("2024-11-10"),
        avarageRating: 4.8,
        duration: 9,
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec est eget purus fermentum varius.",
        maxPeople: 10,
        minAge: 8,
        overview: "Discover Paris's charm.",
        typeId: 3,
        price: 1800,
      },
      {
        name: "Tour 4 in Rome",
        urlImage: "https://mybucketomyproject.s3.us-east-2.amazonaws.com/Roma+(1).jpg",
        countryId: 3,
        cityId: 3,
        initialDate: new Date("2024-12-01"),
        finalDate: new Date("2024-12-10"),
        avarageRating: 4.6,
        duration: 7,
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed scelerisque, dui nec fermentum congue.",
        maxPeople: 15,
        minAge: 12,
        overview: "Explore Rome's ancient wonders.",
        typeId: 1,
        price: 2000,
      },
      {
        name: "Tour 5 in New York",
        urlImage: "https://mybucketomyproject.s3.us-east-2.amazonaws.com/NewYork+(1).jpg",
        countryId: 4,
        cityId: 4,
        initialDate: new Date("2025-01-01"),
        finalDate: new Date("2025-01-10"),
        avarageRating: 4.7,
        duration: 10,
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin efficitur risus ac neque luctus.",
        maxPeople: 20,
        minAge: 15,
        overview: "New York's winter highlights.",
        typeId: 2,
        price: 2200,
      },
      {
        name: "Tour 6 in Rio",
        urlImage: "https://mybucketomyproject.s3.us-east-2.amazonaws.com/Rio+(1).jpg",
        countryId: 1,
        cityId: 2,
        initialDate: new Date("2025-02-01"),
        finalDate: new Date("2025-02-10"),
        avarageRating: 4.8,
        duration: 9,
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus eget libero vitae neque cursus.",
        maxPeople: 10,
        minAge: 10,
        overview: "Celebrate Rio's carnival season.",
        typeId: 3,
        price: 1300,
      },
      {
        name: "Tour 7 in Paris",
        urlImage: "https://mybucketomyproject.s3.us-east-2.amazonaws.com/Paris+(1).jpg",
        countryId: 2,
        cityId: 1,
        initialDate: new Date("2025-03-01"),
        finalDate: new Date("2025-03-10"),
        avarageRating: 4.9,
        duration: 8,
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tristique metus ac nunc fermentum.",
        maxPeople: 12,
        minAge: 12,
        overview: "Experience Paris in the spring.",
        typeId: 1,
        price: 1750,
      },
      {
        name: "Tour 8 in Rome",
        urlImage: "https://mybucketomyproject.s3.us-east-2.amazonaws.com/Roma+(1).jpg",
        countryId: 3,
        cityId: 3,
        initialDate: new Date("2025-04-01"),
        finalDate: new Date("2025-04-10"),
        avarageRating: 4.6,
        duration: 7,
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ut augue vel nisl ultricies pharetra.",
        maxPeople: 15,
        minAge: 5,
        overview: "Discover Rome's historical sites.",
        typeId: 2,
        price: 1600,
      },
      {
        name: "Tour 9 in New York",
        urlImage: "https://mybucketomyproject.s3.us-east-2.amazonaws.com/NewYork+(1).jpg",
        countryId: 4,
        cityId: 4,
        initialDate: new Date("2025-05-01"),
        finalDate: new Date("2025-05-10"),
        avarageRating: 4.7,
        duration: 10,
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla scelerisque nisi et dolor tincidunt.",
        maxPeople: 12,
        minAge: 12,
        overview: "Explore New York's cultural hotspots.",
        typeId: 3,
        price: 2500,
      },
      {
        name: "Tour 10 in Rio",
        urlImage: "https://mybucketomyproject.s3.us-east-2.amazonaws.com/Rio+(1).jpg",
        countryId: 1,
        cityId: 2,
        initialDate: new Date("2025-06-01"),
        finalDate: new Date("2025-06-10"),
        avarageRating: 4.8,
        duration: 9,
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer faucibus neque non ante efficitur.",
        maxPeople: 8,
        minAge: 10,
        overview: "Relax on Rio's famous beaches.",
        typeId: 4,
        price: 1400,
      },
      {
        name: "Tour 11 in New York",
        urlImage: "https://mybucketomyproject.s3.us-east-2.amazonaws.com/NewYork+(1).jpg",
        countryId: 4,
        cityId: 4,
        initialDate: new Date("2025-07-01"),
        finalDate: new Date("2025-07-10"),
        avarageRating: 4.6,
        duration: 8,
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus tincidunt tellus ac libero tincidunt.",
        maxPeople: 10,
        minAge: 7,
        overview: "Summer in New York.",
        typeId: 2,
        price: 1600,
      },
      {
        name: "Tour 12 in Rome",
        urlImage: "https://mybucketomyproject.s3.us-east-2.amazonaws.com/Roma+(1).jpg",
        countryId: 3,
        cityId: 3,
        initialDate: new Date("2025-08-01"),
        finalDate: new Date("2025-08-10"),
        avarageRating: 4.7,
        duration: 9,
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras fringilla massa eu odio euismod.",
        maxPeople: 12,
        minAge: 8,
        overview: "Explore Rome's art and architecture.",
        typeId: 1,
        price: 1900,
      },
      {
        name: "Tour 13 in Paris",
        urlImage: "https://mybucketomyproject.s3.us-east-2.amazonaws.com/Paris+(1).jpg",
        countryId: 2,
        cityId: 1,
        initialDate: new Date("2025-09-01"),
        finalDate: new Date("2025-09-10"),
        avarageRating: 4.8,
        duration: 7,
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin vel risus euismod, scelerisque massa nec.",
        maxPeople: 10,
        minAge: 10,
        overview: "Autumn in Paris.",
        typeId: 3,
        price: 1700,
      },
      {
        name: "Tour 14 in Rio",
        urlImage: "https://mybucketomyproject.s3.us-east-2.amazonaws.com/Rio+(1).jpg",
        countryId: 1,
        cityId: 2,
        initialDate: new Date("2025-10-01"),
        finalDate: new Date("2025-10-10"),
        avarageRating: 4.7,
        duration: 8,
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum eget mauris sit amet eros ultrices.",
        maxPeople: 15,
        minAge: 7,
        overview: "Enjoy Rio's sunny beaches.",
        typeId: 2,
        price: 1500,
      },
      {
        name: "Tour 15 in New York",
        urlImage: "https://mybucketomyproject.s3.us-east-2.amazonaws.com/NewYork+(1).jpg",
        countryId: 4,
        cityId: 4,
        initialDate: new Date("2025-11-01"),
        finalDate: new Date("2025-11-10"),
        avarageRating: 4.6,
        duration: 9,
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at urna euismod, cursus lectus vel.",
        maxPeople: 8,
        minAge: 12,
        overview: "Explore New York's landmarks.",
        typeId: 4,
        price: 2400,
      },
      {
        name: "Tour 16 in Paris",
        urlImage: "https://mybucketomyproject.s3.us-east-2.amazonaws.com/Paris+(1).jpg",
        countryId: 2,
        cityId: 1,
        initialDate: new Date("2025-12-01"),
        finalDate: new Date("2025-12-10"),
        avarageRating: 4.8,
        duration: 10,
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra ipsum in purus interdum.",
        maxPeople: 20,
        minAge: 15,
        overview: "Christmas in Paris.",
        typeId: 1,
        price: 2300,
      },
      {
        name: "Tour 17 in Rome",
        urlImage: "https://mybucketomyproject.s3.us-east-2.amazonaws.com/Roma+(1).jpg",
        countryId: 3,
        cityId: 3,
        initialDate: new Date("2026-01-01"),
        finalDate: new Date("2026-01-10"),
        avarageRating: 4.9,
        duration: 8,
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi vehicula ex at turpis fringilla.",
        maxPeople: 10,
        minAge: 10,
        overview: "Rome's winter magic.",
        typeId: 2,
        price: 2100,
      },
      {
        name: "Tour 18 in Rio",
        urlImage: "https://mybucketomyproject.s3.us-east-2.amazonaws.com/Rio+(1).jpg",
        countryId: 1,
        cityId: 2,
        initialDate: new Date("2026-02-01"),
        finalDate: new Date("2026-02-10"),
        avarageRating: 4.6,
        duration: 9,
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae nisi vehicula, blandit felis.",
        maxPeople: 12,
        minAge: 7,
        overview: "Experience Rio's lively carnival.",
        typeId: 3,
        price: 1700,
      },
      {
        name: "Tour 19 in Paris",
        urlImage: "https://mybucketomyproject.s3.us-east-2.amazonaws.com/Paris+(1).jpg",
        countryId: 2,
        cityId: 1,
        initialDate: new Date("2026-03-01"),
        finalDate: new Date("2026-03-10"),
        avarageRating: 4.7,
        duration: 8,
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam quis nulla ac justo tincidunt.",
        maxPeople: 12,
        minAge: 8,
        overview: "Springtime in Paris.",
        typeId: 1,
        price: 1800,
      },
      {
        name: "Tour 20 in New York",
        urlImage: "https://mybucketomyproject.s3.us-east-2.amazonaws.com/NewYork+(1).jpg",
        countryId: 4,
        cityId: 4,
        initialDate: new Date("2026-04-01"),
        finalDate: new Date("2026-04-10"),
        avarageRating: 4.8,
        duration: 9,
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis tincidunt risus vel eros viverra.",
        maxPeople: 15,
        minAge: 10,
        overview: "Explore New York's spring events.",
        typeId: 2,
        price: 2200,
      },
      {
        name: "Tour 21 in Rio",
        urlImage: "https://mybucketomyproject.s3.us-east-2.amazonaws.com/Rio+(1).jpg",
        countryId: 1,
        cityId: 2,
        initialDate: new Date("2026-05-01"),
        finalDate: new Date("2026-05-10"),
        avarageRating: 4.7,
        duration: 10,
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum lacinia orci nec felis egestas.",
        maxPeople: 10,
        minAge: 12,
        overview: "Experience Rio's vibrant culture.",
        typeId: 3,
        price: 1300,
      },
      {
        name: "Tour 22 in Rome",
        urlImage: "https://mybucketomyproject.s3.us-east-2.amazonaws.com/Roma+(1).jpg",
        countryId: 3,
        cityId: 3,
        initialDate: new Date("2026-06-01"),
        finalDate: new Date("2026-06-10"),
        avarageRating: 4.6,
        duration: 8,
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam erat volutpat. Nulla auctor.",
        maxPeople: 15,
        minAge: 8,
        overview: "Discover Rome's history and art.",
        typeId: 2,
        price: 1600,
      },
      {
        name: "Tour 23 in Paris",
        urlImage: "https://mybucketomyproject.s3.us-east-2.amazonaws.com/Paris+(1).jpg",
        countryId: 2,
        cityId: 1,
        initialDate: new Date("2026-07-01"),
        finalDate: new Date("2026-07-10"),
        avarageRating: 4.8,
        duration: 9,
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec lorem euismod, bibendum neque.",
        maxPeople: 12,
        minAge: 7,
        overview: "Summer in Paris.",
        typeId: 1,
        price: 1900,
      },
      {
        name: "Tour 24 in New York",
        urlImage: "https://mybucketomyproject.s3.us-east-2.amazonaws.com/NewYork+(1).jpg",
        countryId: 4,
        cityId: 4,
        initialDate: new Date("2026-08-01"),
        finalDate: new Date("2026-08-10"),
        avarageRating: 4.9,
        duration: 10,
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam fermentum felis vel dui consectetur.",
        maxPeople: 20,
        minAge: 10,
        overview: "New York in August.",
        typeId: 3,
        price: 2500,
      },
      {
        name: "Tour 25 in Rio",
        urlImage: "https://mybucketomyproject.s3.us-east-2.amazonaws.com/Rio+(1).jpg",
        countryId: 1,
        cityId: 2,
        initialDate: new Date("2026-09-01"),
        finalDate: new Date("2026-09-10"),
        avarageRating: 4.8,
        duration: 9,
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam eget sapien sit amet mi dictum.",
        maxPeople: 8,
        minAge: 5,
        overview: "Relax and enjoy Rio.",
        typeId: 4,
        price: 1400,
      },
      {
        name: "Tour 26 in Rome",
        urlImage: "https://mybucketomyproject.s3.us-east-2.amazonaws.com/Roma+(1).jpg",
        countryId: 3,
        cityId: 3,
        initialDate: new Date("2026-10-01"),
        finalDate: new Date("2026-10-10"),
        avarageRating: 4.7,
        duration: 7,
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut pharetra ligula a dui ornare.",
        maxPeople: 10,
        minAge: 12,
        overview: "Explore Rome's ancient ruins.",
        typeId: 2,
        price: 1700,
      },
      {
        name: "Tour 27 in Paris",
        urlImage: "https://mybucketomyproject.s3.us-east-2.amazonaws.com/Paris+(1).jpg",
        countryId: 2,
        cityId: 1,
        initialDate: new Date("2026-11-01"),
        finalDate: new Date("2026-11-10"),
        avarageRating: 4.6,
        duration: 8,
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque auctor dui nec justo sollicitudin.",
        maxPeople: 15,
        minAge: 10,
        overview: "Paris's autumn colors.",
        typeId: 3,
        price: 1600,
      },
      {
        name: "Tour 28 in New York",
        urlImage: "https://mybucketomyproject.s3.us-east-2.amazonaws.com/NewYork+(1).jpg",
        countryId: 4,
        cityId: 4,
        initialDate: new Date("2026-12-01"),
        finalDate: new Date("2026-12-10"),
        avarageRating: 4.7,
        duration: 9,
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vehicula ex a massa sollicitudin.",
        maxPeople: 10,
        minAge: 12,
        overview: "New York's winter charm.",
        typeId: 4,
        price: 2300,
      },
      {
        name: "Tour 29 in Rio",
        urlImage: "https://mybucketomyproject.s3.us-east-2.amazonaws.com/Rio+(1).jpg",
        countryId: 1,
        cityId: 2,
        initialDate: new Date("2027-01-01"),
        finalDate: new Date("2027-01-10"),
        avarageRating: 4.8,
        duration: 8,
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacinia nisi at nunc facilisis.",
        maxPeople: 12,
        minAge: 7,
        overview: "New Year in Rio.",
        typeId: 1,
        price: 1550,
      },
      {
        name: "Tour 30 in Rome",
        urlImage: "https://mybucketomyproject.s3.us-east-2.amazonaws.com/Roma+(1).jpg",
        countryId: 3,
        cityId: 3,
        initialDate: new Date("2027-02-01"),
        finalDate: new Date("2027-02-10"),
        avarageRating: 4.9,
        duration: 9,
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis condimentum erat eu sapien feugiat.",
        maxPeople: 10,
        minAge: 5,
        overview: "Rome in February.",
        typeId: 1,
        price: 1750,
      },
    ],
  });

  console.log("Tours created!");
}

main()
  .catch((e) => {
    console.error(e);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });