import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

async function main() {

  await prisma.continent.createMany({
    data: [{ name: "Europe" }, { name: "North America" }, { name: "South America" }],
  });


  await prisma.country.createMany({
    data: [{ name: "Brazil", continentId: 3, }, { name: "France", continentId: 1, }, { name: "Italy", continentId: 1, }, { name: "USA", continentId: 2, }],
  });

  await prisma.city.createMany({
    data: [
      { name: "Paris", countryId: 2 },
      { name: "Rio de Janeiro", countryId: 1 },
      { name: "Rome", countryId: 3 },
      { name: "New York", countryId: 4 },
    ],
  });

  await prisma.types.createMany({
    data: [{ name: "Adventure" }, { name: "Cultural" }, { name: "Historical" }, { name: "Relaxing" }],
  });

  await prisma.tour.createMany({
    data: [
      {
        name: "Tour 1 in New York",
        urlImage: "url_image_example_1.jpg",
        countryId: 4,
        cityId: 4,
        initialDate: new Date("2024-09-01"),
        finalDate: new Date("2024-09-10"),
        avarageRating: 4.5,
        duration: 7,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus imperdiet, nulla vel tempor consectetur, arcu nisl tempor odio, nec lacinia justo justo a nunc. Nulla facilisi. Vestibulum at diam a odio ultricies laoreet. Mauris mollis, lacus eget euismod laoreet, sapien libero facilisis est, et tincidunt elit velit id augue. Aliquam erat volutpat. Proin efficitur magna et justo cursus, vel maximus turpis faucibus.",
        maxPeople: 10,
        minAge: 5,
        overview: "Experience the best of New York.",
        typeId: 1,
      },
      {
        name: "Tour 2 in Rio",
        urlImage: "url_image_example_2.jpg",
        countryId: 1,
        cityId: 2,
        initialDate: new Date("2024-10-01"),
        finalDate: new Date("2024-10-10"),
        avarageRating: 4.7,
        duration: 8,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque nec diam et turpis pretium tincidunt. Fusce sollicitudin nisi non cursus ultrices. Sed ut lacinia libero. Donec a mauris a velit cursus euismod vel at dui. In ac gravida mauris. Donec accumsan fringilla efficitur. Suspendisse potenti.",
        maxPeople: 12,
        minAge: 7,
        overview: "Enjoy Rio's vibrant atmosphere.",
        typeId: 2,
      },
      {
        name: "Tour 3 in Paris",
        urlImage: "url_image_example_3.jpg",
        countryId: 2,
        cityId: 1,
        initialDate: new Date("2024-11-01"),
        finalDate: new Date("2024-11-10"),
        avarageRating: 4.8,
        duration: 9,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec est eget purus fermentum varius. Nullam at sem efficitur, gravida dui at, pellentesque dui. Nam sed felis vitae libero sollicitudin auctor. Vestibulum vulputate ultricies nunc, non hendrerit elit dignissim a. Praesent sed est libero. Morbi ac metus et odio sodales vestibulum.",
        maxPeople: 10,
        minAge: 8,
        overview: "Discover Paris's charm.",
        typeId: 3,
      },
      {
        name: "Tour 4 in Rome",
        urlImage: "url_image_example_4.jpg",
        countryId: 3,
        cityId: 3,
        initialDate: new Date("2024-12-01"),
        finalDate: new Date("2024-12-10"),
        avarageRating: 4.6,
        duration: 7,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed scelerisque, dui nec fermentum congue, mi augue vehicula erat, id vehicula dolor nunc et velit. Nullam euismod, sem at luctus hendrerit, lacus erat dictum libero, non ullamcorper augue augue sit amet lorem. Integer id lacus eu urna cursus cursus.",
        maxPeople: 15,
        minAge: 12,
        overview: "Explore Rome's ancient wonders.",
        typeId: 1,
      },
      {
        name: "Tour 5 in New York",
        urlImage: "url_image_example_5.jpg",
        countryId: 4,
        cityId: 4,
        initialDate: new Date("2025-01-01"),
        finalDate: new Date("2025-01-10"),
        avarageRating: 4.7,
        duration: 10,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin efficitur risus ac neque luctus, nec pellentesque dolor sodales. Aliquam erat volutpat. Sed at convallis sapien. Donec a luctus quam. Vivamus a dolor at eros sollicitudin vestibulum sit amet et purus. Donec vulputate gravida metus ut vulputate.",
        maxPeople: 20,
        minAge: 15,
        overview: "New York's winter highlights.",
        typeId: 2,
      },
      {
        name: "Tour 6 in Rio",
        urlImage: "url_image_example_6.jpg",
        countryId: 1,
        cityId: 2,
        initialDate: new Date("2025-02-01"),
        finalDate: new Date("2025-02-10"),
        avarageRating: 4.8,
        duration: 9,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus eget libero vitae neque cursus consectetur et sit amet nisl. Aliquam tristique ligula nec quam aliquam, a venenatis arcu cursus. Phasellus auctor orci in nunc fermentum feugiat. Integer eu nibh id dolor luctus facilisis. Suspendisse potenti.",
        maxPeople: 10,
        minAge: 10,
        overview: "Celebrate Rio's carnival season.",
        typeId: 3,
      },
      {
        name: "Tour 7 in Paris",
        urlImage: "url_image_example_7.jpg",
        countryId: 2,
        cityId: 1,
        initialDate: new Date("2025-03-01"),
        finalDate: new Date("2025-03-10"),
        avarageRating: 4.9,
        duration: 8,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tristique metus ac nunc fermentum, vel gravida tortor tempor. Nulla ultricies efficitur urna, non egestas lorem tincidunt vel. Cras quis turpis ut nunc maximus gravida. Vestibulum euismod sapien vitae ex dictum scelerisque.",
        maxPeople: 12,
        minAge: 12,
        overview: "Experience Paris in the spring.",
        typeId: 1,
      },
      {
        name: "Tour 8 in Rome",
        urlImage: "url_image_example_8.jpg",
        countryId: 3,
        cityId: 3,
        initialDate: new Date("2025-04-01"),
        finalDate: new Date("2025-04-10"),
        avarageRating: 4.6,
        duration: 7,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ut augue vel nisl ultricies pharetra. Integer ac magna vitae eros pretium lacinia. Donec fermentum sem ac est varius vestibulum. Morbi venenatis urna sit amet ligula pharetra, ac dictum arcu elementum.",
        maxPeople: 15,
        minAge: 5,
        overview: "Discover Rome's historical sites.",
        typeId: 2,
      },
      {
        name: "Tour 9 in New York",
        urlImage: "url_image_example_9.jpg",
        countryId: 4,
        cityId: 4,
        initialDate: new Date("2025-05-01"),
        finalDate: new Date("2025-05-10"),
        avarageRating: 4.7,
        duration: 10,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla scelerisque nisi et dolor tincidunt, sed efficitur elit eleifend. Fusce auctor, lacus et volutpat commodo, magna odio dignissim mauris, et blandit orci arcu et ligula. Vestibulum et ligula a metus ultrices vehicula.",
        maxPeople: 12,
        minAge: 12,
        overview: "Explore New York's cultural hotspots.",
        typeId: 3,
      },
      {
        name: "Tour 10 in Rio",
        urlImage: "url_image_example_10.jpg",
        countryId: 1,
        cityId: 2,
        initialDate: new Date("2025-06-01"),
        finalDate: new Date("2025-06-10"),
        avarageRating: 4.8,
        duration: 8,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam interdum purus et turpis efficitur, nec facilisis libero dapibus. Integer a purus nec erat feugiat eleifend. Aenean vitae urna ac risus suscipit tempor. Nullam ut augue et est tincidunt convallis.",
        maxPeople: 10,
        minAge: 10,
        overview: "Enjoy Rio's summer festivals.",
        typeId: 1,
      },
      {
        name: "Tour 11 in Paris",
        urlImage: "url_image_example_11.jpg",
        countryId: 2,
        cityId: 1,
        initialDate: new Date("2025-07-01"),
        finalDate: new Date("2025-07-10"),
        avarageRating: 4.9,
        duration: 7,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi auctor velit sed turpis cursus, ac vehicula lorem commodo. Donec sit amet quam et risus pharetra lacinia. Vestibulum venenatis metus vitae mi convallis, ac faucibus elit lacinia. Ut condimentum lorem sit amet quam bibendum.",
        maxPeople: 15,
        minAge: 8,
        overview: "Experience Paris in summer.",
        typeId: 2,
      },
      {
        name: "Tour 12 in Rome",
        urlImage: "url_image_example_12.jpg",
        countryId: 3,
        cityId: 3,
        initialDate: new Date("2025-08-01"),
        finalDate: new Date("2025-08-10"),
        avarageRating: 4.5,
        duration: 9,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras nec interdum ligula. Fusce efficitur, velit a posuere convallis, nunc ligula posuere metus, a tincidunt est ligula id ligula. Duis quis bibendum odio. Proin sed nisi vel augue pretium efficitur.",
        maxPeople: 20,
        minAge: 15,
        overview: "Explore Rome's summer charm.",
        typeId: 3,
      },
      {
        name: "Tour 13 in New York",
        urlImage: "url_image_example_13.jpg",
        countryId: 4,
        cityId: 4,
        initialDate: new Date("2025-09-01"),
        finalDate: new Date("2025-09-10"),
        avarageRating: 4.6,
        duration: 8,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec faucibus dolor nec libero vehicula, vel tincidunt ex ornare. Aliquam erat volutpat. In hac habitasse platea dictumst. Cras pretium leo in orci eleifend, nec lacinia libero convallis.",
        maxPeople: 10,
        minAge: 7,
        overview: "New York in the fall.",
        typeId: 1,
      },
      {
        name: "Tour 14 in Rio",
        urlImage: "url_image_example_14.jpg",
        countryId: 1,
        cityId: 2,
        initialDate: new Date("2025-10-01"),
        finalDate: new Date("2025-10-10"),
        avarageRating: 4.7,
        duration: 10,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tristique, nunc nec volutpat posuere, tortor lacus vehicula velit, eu condimentum orci justo at felis. Nullam sit amet purus ut dolor iaculis dignissim. Vivamus tempor sagittis elit eu efficitur.",
        maxPeople: 12,
        minAge: 10,
        overview: "Enjoy Rio's fall attractions.",
        typeId: 2,
      },
      {
        name: "Tour 15 in Paris",
        urlImage: "url_image_example_15.jpg",
        countryId: 2,
        cityId: 1,
        initialDate: new Date("2025-11-01"),
        finalDate: new Date("2025-11-10"),
        avarageRating: 4.8,
        duration: 7,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam fringilla, felis in vehicula lacinia, turpis magna tincidunt mi, nec venenatis libero ligula a justo. Aenean viverra, orci ac fringilla auctor, nulla quam pharetra nisi, in laoreet nulla sapien eget ligula.",
        maxPeople: 15,
        minAge: 12,
        overview: "Experience Paris's autumn beauty.",
        typeId: 3,
      },
      {
        name: "Tour 16 in Rome",
        urlImage: "url_image_example_16.jpg",
        countryId: 3,
        cityId: 3,
        initialDate: new Date("2025-12-01"),
        finalDate: new Date("2025-12-10"),
        avarageRating: 4.5,
        duration: 8,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis venenatis, felis id vehicula vestibulum, arcu elit sagittis libero, a hendrerit urna elit sit amet lacus. Donec dapibus malesuada nisl id gravida. Vivamus gravida risus eu nulla maximus, non facilisis est efficitur.",
        maxPeople: 10,
        minAge: 5,
        overview: "Explore Rome's winter sights.",
        typeId: 1,
      },
      {
        name: "Tour 17 in New York",
        urlImage: "url_image_example_17.jpg",
        countryId: 4,
        cityId: 4,
        initialDate: new Date("2026-01-01"),
        finalDate: new Date("2026-01-10"),
        avarageRating: 4.6,
        duration: 7,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum at orci quis libero ullamcorper feugiat. Nullam lacinia, libero id euismod auctor, eros nunc consectetur mi, at blandit lorem sapien sed ipsum. Vivamus gravida urna sit amet lectus volutpat.",
        maxPeople: 15,
        minAge: 7,
        overview: "Discover New York in the new year.",
        typeId: 2,
      },
      {
        name: "Tour 18 in Rio",
        urlImage: "url_image_example_18.jpg",
        countryId: 1,
        cityId: 2,
        initialDate: new Date("2026-02-01"),
        finalDate: new Date("2026-02-10"),
        avarageRating: 4.7,
        duration: 10,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam vitae mauris eget est venenatis faucibus. Ut eu orci ac augue cursus elementum. Donec interdum urna eu velit consectetur, sed tincidunt odio auctor. Pellentesque at sem eu arcu volutpat ultricies.",
        maxPeople: 12,
        minAge: 8,
        overview: "Experience Rio's February festivities.",
        typeId: 3,
      },
      {
        name: "Tour 19 in Paris",
        urlImage: "url_image_example_19.jpg",
        countryId: 2,
        cityId: 1,
        initialDate: new Date("2026-03-01"),
        finalDate: new Date("2026-03-10"),
        avarageRating: 4.8,
        duration: 9,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer mollis turpis et sem vulputate, vel eleifend purus varius. Cras quis tortor nec lectus ullamcorper consequat. Aliquam vestibulum nisi et turpis tincidunt, at cursus purus placerat.",
        maxPeople: 10,
        minAge: 10,
        overview: "Springtime in Paris awaits.",
        typeId: 1,
      },
      {
        name: "Tour 20 in Rome",
        urlImage: "url_image_example_20.jpg",
        countryId: 3,
        cityId: 3,
        initialDate: new Date("2026-04-01"),
        finalDate: new Date("2026-04-10"),
        avarageRating: 4.6,
        duration: 8,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vestibulum lectus vel lorem aliquet, non pharetra nulla pretium. Nam ultricies, tortor sit amet lacinia euismod, metus velit viverra est, sit amet tincidunt eros ligula ut urna. Duis suscipit cursus nisi, a facilisis lectus.",
        maxPeople: 15,
        minAge: 12,
        overview: "Explore Rome's spring beauty.",
        typeId: 2,
      },
      {
        name: "Tour 21 in New York",
        urlImage: "url_image_example_21.jpg",
        countryId: 4,
        cityId: 4,
        initialDate: new Date("2026-05-01"),
        finalDate: new Date("2026-05-10"),
        avarageRating: 4.7,
        duration: 7,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sollicitudin metus eu ex pretium, sed tincidunt mauris convallis. Vivamus eu ligula vitae lacus posuere cursus. Aliquam non velit at orci vulputate pharetra. Vestibulum ac magna ultricies, dictum elit eu, suscipit ligula.",
        maxPeople: 20,
        minAge: 5,
        overview: "Enjoy New York's summer events.",
        typeId: 3,
      },
      {
        name: "Tour 22 in Rio",
        urlImage: "url_image_example_22.jpg",
        countryId: 1,
        cityId: 2,
        initialDate: new Date("2026-06-01"),
        finalDate: new Date("2026-06-10"),
        avarageRating: 4.8,
        duration: 10,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam venenatis felis ut nisi suscipit, nec malesuada purus aliquam. Suspendisse a sapien at quam vehicula ultrices. Morbi euismod ligula nec lacus pharetra, eu euismod dolor malesuada.",
        maxPeople: 12,
        minAge: 8,
        overview: "Rio's summer highlights.",
        typeId: 1,
      },
      {
        name: "Tour 23 in Paris",
        urlImage: "url_image_example_23.jpg",
        countryId: 2,
        cityId: 1,
        initialDate: new Date("2026-07-01"),
        finalDate: new Date("2026-07-10"),
        avarageRating: 4.9,
        duration: 9,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam tincidunt libero ut magna fringilla, id pellentesque magna commodo. Nullam euismod risus at erat accumsan, non tincidunt felis blandit. Donec vehicula lectus sit amet vehicula cursus.",
        maxPeople: 15,
        minAge: 10,
        overview: "Paris in the summer sun.",
        typeId: 2,
      },
      {
        name: "Tour 24 in Rome",
        urlImage: "url_image_example_24.jpg",
        countryId: 3,
        cityId: 3,
        initialDate: new Date("2026-08-01"),
        finalDate: new Date("2026-08-10"),
        avarageRating: 4.6,
        duration: 8,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In euismod sem in ligula venenatis, sed vehicula arcu aliquet. Donec dapibus orci euismod nisi aliquam, nec vestibulum nisl auctor. Phasellus luctus mi id ligula ultrices, sed luctus dui facilisis.",
        maxPeople: 10,
        minAge: 5,
        overview: "Discover Rome's summer splendor.",
        typeId: 3,
      },
      {
        name: "Tour 25 in New York",
        urlImage: "url_image_example_25.jpg",
        countryId: 4,
        cityId: 4,
        initialDate: new Date("2026-09-01"),
        finalDate: new Date("2026-09-10"),
        avarageRating: 4.7,
        duration: 7,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ultrices purus non tortor malesuada, ut cursus erat sodales. Quisque vestibulum nunc eget mauris cursus, et consectetur sem consectetur. Ut consequat odio ac velit laoreet aliquet.",
        maxPeople: 10,
        minAge: 7,
        overview: "New York's autumn wonders.",
        typeId: 1,
      },
      {
        name: "Tour 26 in Rio",
        urlImage: "url_image_example_26.jpg",
        countryId: 1,
        cityId: 2,
        initialDate: new Date("2026-10-01"),
        finalDate: new Date("2026-10-10"),
        avarageRating: 4.8,
        duration: 10,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras auctor dolor ut magna cursus, a consequat urna luctus. Nulla facilisi. Vivamus imperdiet magna ac turpis varius, et iaculis neque lacinia. Morbi id felis eu nunc fringilla ullamcorper.",
        maxPeople: 12,
        minAge: 8,
        overview: "Enjoy Rio's October festivities.",
        typeId: 2,
      },
      {
        name: "Tour 27 in Paris",
        urlImage: "url_image_example_27.jpg",
        countryId: 2,
        cityId: 1,
        initialDate: new Date("2026-11-01"),
        finalDate: new Date("2026-11-10"),
        avarageRating: 4.9,
        duration: 9,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer ut sollicitudin nulla, et facilisis odio. Phasellus quis sem nec lectus maximus pretium. Morbi sagittis, nisi nec venenatis varius, arcu felis dapibus sapien, non ullamcorper dolor lectus ut urna.",
        maxPeople: 15,
        minAge: 12,
        overview: "Paris in the fall season.",
        typeId: 3,
      },
      {
        name: "Tour 28 in Rome",
        urlImage: "url_image_example_28.jpg",
        countryId: 3,
        cityId: 3,
        initialDate: new Date("2026-12-01"),
        finalDate: new Date("2026-12-10"),
        avarageRating: 4.5,
        duration: 8,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla facilisi. In scelerisque dolor nec metus tincidunt, vel aliquet urna gravida. Quisque at bibendum velit. Vestibulum nec lectus auctor, dictum eros at, scelerisque turpis.",
        maxPeople: 10,
        minAge: 5,
        overview: "Rome's winter experiences await.",
        typeId: 1,
      },
      {
        name: "Tour 29 in New York",
        urlImage: "url_image_example_29.jpg",
        countryId: 4,
        cityId: 4,
        initialDate: new Date("2027-01-01"),
        finalDate: new Date("2027-01-10"),
        avarageRating: 4.6,
        duration: 7,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis interdum, justo ac sagittis condimentum, mi sapien sagittis arcu, sed venenatis tortor velit nec magna. Integer lacinia arcu sit amet nisi vestibulum, sit amet aliquet erat consectetur.",
        maxPeople: 15,
        minAge: 10,
        overview: "New York's winter attractions.",
        typeId: 2,
      },
      {
        name: "Tour 30 in Rio",
        urlImage: "url_image_example_30.jpg",
        countryId: 1,
        cityId: 2,
        initialDate: new Date("2027-02-01"),
        finalDate: new Date("2027-02-10"),
        avarageRating: 4.7,
        duration: 10,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sed urna nec elit luctus cursus. Vivamus euismod, dui ac dictum lacinia, magna ligula luctus nisl, non suscipit purus elit eget risus. Sed condimentum nunc at justo dictum, non venenatis ligula lacinia.",
        maxPeople: 12,
        minAge: 12,
        overview: "Rio's February festivities.",
        typeId: 3,
      },
    ],
  });
  await prisma.user.createMany({
    data: [
      {
        id: "user1",
        email: "vinicius@gmail.com",
        name: "Vinicius",
      }]
  })

  await prisma.review.createMany({
    data: [
      {
        services: 5.0,
        location: 5.0,
        Amenities: 4.5,
        Prices: 4.0,
        Food: 4.5,
        comfort: 4.0,
        description: "Amazing tour with excellent guides!",
        tourId: 1,
        userId: "user1",
        createdAt: new Date("2024-02-15"),
      },
      {
        services: 4.5,
        location: 4.8,
        Amenities: 4.0,
        Prices: 4.5,
        Food: 4.2,
        comfort: 4.5,
        description: "Very good experience, but a bit expensive.",
        tourId: 2,
        userId: "user1",
        createdAt: new Date("2024-05-05"),
      },
    ],
  });

  
}



main()
  .catch((e) => {
    console.error(e);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
